from flask import Flask, render_template, request, redirect
from datetime import datetime
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///FHS_Survey.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db = SQLAlchemy(app)

# Creating the schema of our database

#Create Technical Installation Table Here:

class Technical_Installation(db.Model):
    TechnicalInstallationID = db.Column(db.Integer, primary_key=True)
    CustomerName = db.Column(db.String(200))
    CustomerSite = db.Column(db.String(50))
    Date = db.Column(db.String, default=lambda: datetime.now().strftime("%d/%m/%Y"))
    Time = db.Column(db.String, default=lambda: datetime.now().strftime("%I:%M %p"))
    JobNumber = db.Column(db.String(50))
    InvoiceNumber = db.Column(db.String(50))
    PlantMake = db.Column(db.String(50))
    PlantModel = db.Column(db.String(50))
    SerialNumber = db.Column(db.String(50))
    EngineMake = db.Column(db.String(50))
    EngineModel = db.Column(db.String(50))
    EngineSerialNumber = db.Column(db.String(50))
    PlantNumber = db.Column(db.String(50))
    PlantKmsHrs = db.Column(db.String(50))
    WarrantyStartDate = db.Column(db.String(50))
    WarrantyEndDate = db.Column(db.String(50))
    InstallationPhoto1 = db.Column(db.String(50))
    InstallationPhoto2 = db.Column(db.String(50))
    InstallationPhoto3 = db.Column(db.String(50))
    InstallationPhoto4 = db.Column(db.String(50))
    InstallationPhoto5 = db.Column(db.String(50))
    InstallationPhoto6 = db.Column(db.String(50))
    AdditionalCommentsSuggestions = db.Column(db.String(50))
    CustomerFullName = db.Column(db.String(50))
    CustomerDate = db.Column(db.String(50))
    TechnitianFullName = db.Column(db.String(50))
    TechnitianDate = db.Column(db.String(50))
    EmailReportTo = db.Column(db.String(50))

    # Display the details of our code
    def __repr__(self) -> str:
        return f"{self.technicalInstallationID} {self.CustomerName}"

# Create Exhaust Inspection Table Here:

class Exhaust_Inspection(db.Model):
    ExhaustInspectionID = db.Column(db.Integer, primary_key=True)
    CustomerName = db.Column(db.String(200))
    CustomerSite = db.Column(db.String(50))
    Date = db.Column(db.String, default=lambda: datetime.now().strftime("%d/%m/%Y"))
    Time = db.Column(db.String, default=lambda: datetime.now().strftime("%I:%M %p"))
    ContactPerson = db.Column(db.String(200))
    InspectedBy = db.Column(db.String(200))
    InspectionAssistant = db.Column(db.String(50))
    PlantNumber = db.Column(db.String(200))
    PlantMake = db.Column(db.String(50))
    PlantModel = db.Column(db.String(200))
    SerialNumber = db.Column(db.String(50))
    PlantKmsHrs = db.Column(db.String(50))
    EngineMake = db.Column(db.String(50))
    EngineModel = db.Column(db.String(50))
    EngineSerialNumber = db.Column(db.String(50))
    ExhaustMufflerPartNumber = db.Column(db.String(50))
    PhotoOfExhaustMuffler = db.Column(db.String(50))
    CommentsOnExhaustMuffler = db.Column(db.String(50))
    ExhaustPipePartNumber1 = db.Column(db.String(50))
    PhotoOfExhaustPipe1 = db.Column(db.String(50))
    CommentsOnExhaustPipe1 = db.Column(db.String(50))
    ExhaustPipePartNumber2 = db.Column(db.String(50))
    PhotoOfExhaustPipe2 = db.Column(db.String(50))
    CommentsOnExhaustPipe2 = db.Column(db.String(50))
    ExhaustPipePartNumber3 = db.Column(db.String(50))
    PhotoOfExhaustPipe3 = db.Column(db.String(50))
    CommentsOnExhaustPipe3 = db.Column(db.String(50))
    ExhaustPipePartNumber4 = db.Column(db.String(50))
    PhotoOfExhaustPipe4 = db.Column(db.String(50))
    CommentsOnExhaustPipe4 = db.Column(db.String(50))
    ExhaustPipePartNumber5 = db.Column(db.String(50))
    PhotoOfExhaustPipe5 = db.Column(db.String(50))
    CommentsOnExhaustPipe5 = db.Column(db.String(50))
    ExhaustPipePartNumber6 = db.Column(db.String(50))
    CommentsOnExhaustPipe6 = db.Column(db.String(50))
    PhotoOfExhaustPipe6 = db.Column(db.String(50))
    ExhaustPipePartNumber7 = db.Column(db.String(50))
    PhotoOfExhaustPipe7 = db.Column(db.String(50))
    CommentsOnExhaustPipe7 = db.Column(db.String(50))
    ExhaustPipePartNumber8 = db.Column(db.String(50))
    PhotoOfExhaustPipe8 = db.Column(db.String(50))
    CommentsOnExhaustPipe8 = db.Column(db.String(50))
    GeneralComments = db.Column(db.String(50))
    EmailReportTo = db.Column(db.String(50))

    # Display the details of our code
    def __repr__(self) -> str:
        return f"{self.ExhaustInspectionID} {self.CustomerName}"

#Create Plant Inspection Table Here:
class Plant_Inspection(db.Model):
    PlantInspectionID = db.Column(db.Integer, primary_key=True)
    CustomerName = db.Column(db.String(200))
    CustomerSite = db.Column(db.String(50))
    Date = db.Column(db.String, default=lambda: datetime.now().strftime("%d/%m/%Y"))
    Time = db.Column(db.String, default=lambda: datetime.now().strftime("%I:%M %p"))
    ContactPerson = db.Column(db.String(50))
    InspectedBy = db.Column(db.String(50))
    InspectionAssistant = db.Column(db.String(50))
    PlantNumber = db.Column(db.String(50))
    PlantMake = db.Column(db.String(50))
    PlantModel = db.Column(db.String(50))
    SerialNumber = db.Column(db.String(50))
    PlantKmsHrs = db.Column(db.String(50))
    EngineMake = db.Column(db.String(50))
    EngineModel = db.Column(db.String(50))
    EngineSerialNumber = db.Column(db.String(50))
    PriamryFuelFilterPartNumber = db.Column(db.String(50))
    PrimaryFuelFilterPhoto = db.Column(db.String(50))
    CommentsOnFuelFilter = db.Column(db.String(50))
    SecondaryFuelFilterPartNumber = db.Column(db.String(50))
    SecondaryFuelFilterPhoto = db.Column(db.String(50))
    CommentsOnSecondaryFuelFilter = db.Column(db.String(50))
    FuelWaterSeparatorPartNumber = db.Column(db.String(50))
    PhotoOfFuelWaterSeparator = db.Column(db.String(50))
    CommentsOnFuelWaterSeparator = db.Column(db.String(50))
    OilFilterPartNumber = db.Column(db.String(50))
    PhotoOfOilFilter = db.Column(db.String(50))
    CommentsOnOilFilter = db.Column(db.String(50))
    BypassOilFilterPartNumber = db.Column(db.String(50))
    PhotoOfBypassOilFilter = db.Column(db.String(50))
    CommentsOnBypassOilFilter = db.Column(db.String(50))
    HydraulicFilterPartNumber1 = db.Column(db.String(50))
    PhotoOfHydraulicFilter1 = db.Column(db.String(50))
    CommentsOnHydraulicFilter1 = db.Column(db.String(50))
    HydraulicFilterPartNumber2 = db.Column(db.String(50))
    PhotoOfHydraulicFilter2 = db.Column(db.String(50))
    CommentsOnHydraulicFilter2 = db.Column(db.String(50))
    HydraulicFilterPartNumber3 = db.Column(db.String(50))
    PhotoOfHydraulicFilter3 = db.Column(db.String(50))
    CommentsOnHydraulicFilter3 = db.Column(db.String(50))
    HydraulicFilterPartNumber4 = db.Column(db.String(50))
    PhotoOfHydraulicFilter4 = db.Column(db.String(50))
    CommentsOnHydraulicFilter4 = db.Column(db.String(50))
    HydraulicFilterPartNumber5 = db.Column(db.String(50))
    PhotoOfHydraulicFilter5 = db.Column(db.String(50))
    CommentsOnHydraulicFilter5 = db.Column(db.String(50))
    HydraulicFilterPartNumber6 = db.Column(db.String(50))
    PhotoOfHydraulicFilter6 = db.Column(db.String(50))
    CommentsOnHydraulicFilter6 = db.Column(db.String(50))
    HydraulicFilterPartNumber7 = db.Column(db.String(50))
    PhotoOfHydraulicFilter7 = db.Column(db.String(50))
    CommentsOnHydraulicFilter7 = db.Column(db.String(50))
    HydraulicFilterPartNumber8 = db.Column(db.String(50))
    PhotoOfHydraulicFilter8 = db.Column(db.String(50))
    CommentsOnHydraulicFilter8 = db.Column(db.String(50))
    TransmissionFilterPartNumber1 = db.Column(db.String(50))
    PhotoOfTransmissionFilter1 = db.Column(db.String(50))
    CommentsOnTransmissionFilter1 = db.Column(db.String(50))
    TransmissionFilterPartNumber2 = db.Column(db.String(50))
    PhotoOfTransmissionFilter2 = db.Column(db.String(50))
    CommentsOnTransmissionFilter2 = db.Column(db.String(50))
    TransmissionFilterPartNumber3 = db.Column(db.String(50))
    PhotoOfTransmissionFilter3 = db.Column(db.String(50))
    CommentsOnTransmissionFilter3 = db.Column(db.String(50))
    TransmissionFilterPartNumber4 = db.Column(db.String(50))
    PhotoOfTransmissionFilter4 = db.Column(db.String(50))
    CommentsOnTransmissionFilter4 = db.Column(db.String(50))
    TransmissionFilterPartNumber5 = db.Column(db.String(50))
    PhotoOfTransmissionFilter5 = db.Column(db.String(50))
    CommentsOnTransmissionFilter5 = db.Column(db.String(50))
    TransmissionFilterPartNumber6 = db.Column(db.String(50))
    PhotoOfTransmissionFilter6 = db.Column(db.String(50))
    CommentsOnTransmissionFilter6 = db.Column(db.String(50))
    TransmissionFilterPartNumber7 = db.Column(db.String(50))
    PhotoOfTransmissionFilter7 = db.Column(db.String(50))
    CommentsOnTransmissionFilter7 = db.Column(db.String(50))
    TransmissionFilterPartNumber8 = db.Column(db.String(50))
    PhotoOfTransmissionFilter8 = db.Column(db.String(50))
    CommentsOnTransmissionFilter8 = db.Column(db.String(50))
    CoolantFiltersPartNumber1 = db.Column(db.String(50))
    PhotoOfCoolantFilter1 = db.Column(db.String(50))
    CommentsOnCoolantFilter1 = db.Column(db.String(50))
    CoolantFiltersPartNumber2 = db.Column(db.String(50))
    PhotoOfCoolantFilter2 = db.Column(db.String(50))
    CommentsOnCoolantFilter2 = db.Column(db.String(50))
    CoolantFiltersPartNumber3 = db.Column(db.String(50))
    PhotoOfCoolantFilter3 = db.Column(db.String(50))
    CommentsOnCoolantFilter3 = db.Column(db.String(50))
    CoolantFiltersPartNumber4 = db.Column(db.String(50))
    PhotoOfCoolantFilter4 = db.Column(db.String(50))
    CommentsOnCoolantFilter4 = db.Column(db.String(50))
    CoolantFiltersPartNumber5 = db.Column(db.String(50))
    PhotoOfCoolantFilter5 = db.Column(db.String(50))
    CommentsOnCoolantFilter5 = db.Column(db.String(50))
    CoolantFiltersPartNumber6 = db.Column(db.String(50))
    PhotoOfCoolantFilter6 = db.Column(db.String(50))
    CommentsOnCoolantFilter6 = db.Column(db.String(50))
    CoolantFiltersPartNumber7 = db.Column(db.String(50))
    PhotoOfCoolantFilter7 = db.Column(db.String(50))
    CommentsOnCoolantFilter7 = db.Column(db.String(50))
    CoolantFiltersPartNumber8 = db.Column(db.String(50))
    PhotoOfCoolantFilter8 = db.Column(db.String(50))
    CommentsOnCoolantFilter8 = db.Column(db.String(50))
    BreatherFilterPartNumber1 = db.Column(db.String(50))
    PhotoOfBreatherFilter1 = db.Column(db.String(50))
    CommentsOnBreatherFilter1 = db.Column(db.String(50))
    BreatherFilterPartNumber2 = db.Column(db.String(50))
    PhotoOfBreatherFilter2 = db.Column(db.String(50))
    CommentsOnBreatherFilter2 = db.Column(db.String(50))
    BreatherFilterPartNumber3 = db.Column(db.String(50))
    PhotoOfBreatherFilter3 = db.Column(db.String(50))
    CommentsOnBreatherFilter3 = db.Column(db.String(50))
    BreatherFilterPartNumber4 = db.Column(db.String(50))
    PhotoOfBreatherFilter4 = db.Column(db.String(50))
    CommentsOnBreatherFilter4 = db.Column(db.String(50))
    BreatherFilterPartNumber5 = db.Column(db.String(50))
    PhotoOfBreatherFilter5 = db.Column(db.String(50))
    CommentsOnBreatherFilter5 = db.Column(db.String(50))
    BreatherFilterPartNumber6 = db.Column(db.String(50))
    PhotoOfBreatherFilter6 = db.Column(db.String(50))
    CommentsOnBreatherFilter6 = db.Column(db.String(50))
    BreatherFilterPartNumber7 = db.Column(db.String(50))
    PhotoOfBreatherFilter7 = db.Column(db.String(50))
    CommentsOnBreatherFilter7 = db.Column(db.String(50))
    BreatherFilterPartNumber8 = db.Column(db.String(50))
    PhotoOfBreatherFilter8 = db.Column(db.String(50))
    CommentsOnBreatherFilter8 = db.Column(db.String(50))
    AirDryerPartNumber1 = db.Column(db.String(50))
    PhotoOfAirDryer1 = db.Column(db.String(50))
    CommentsOfAirDryer1 = db.Column(db.String(50))
    AirDryerPartNumber2 = db.Column(db.String(50))
    PhotoOfAirDryer2 = db.Column(db.String(50))
    CommentsOfAirDryer2 = db.Column(db.String(50))
    AirDryerPartNumber3 = db.Column(db.String(50))
    PhotoOfAirDryer3 = db.Column(db.String(50))
    CommentsOfAirDryer3 = db.Column(db.String(50))
    AirDryerPartNumber4 = db.Column(db.String(50))
    PhotoOfAirDryer4 = db.Column(db.String(50))
    CommentsOfAirDryer4 = db.Column(db.String(50))
    AirDryerPartNumber5 = db.Column(db.String(50))
    PhotoOfAirDryer5 = db.Column(db.String(50))
    CommentsOfAirDryer5 = db.Column(db.String(50))
    AirDryerPartNumber6 = db.Column(db.String(50))
    PhotoOfAirDryer6 = db.Column(db.String(50))
    CommentsOfAirDryer6 = db.Column(db.String(50))
    AirDryerPartNumber7 = db.Column(db.String(50))
    PhotoOfAirDryer7 = db.Column(db.String(50))
    CommentsOfAirDryer7 = db.Column(db.String(50))
    AirDryerPartNumber8 = db.Column(db.String(50))
    PhotoOfAirDryer8 = db.Column(db.String(50))
    CommentsOfAirDryer8 = db.Column(db.String(50))
    CabinFilterPartNumber1 = db.Column(db.String(50))
    PhotoOfCabinFilter1 = db.Column(db.String(50))
    CommentsOnCabinFilter1 = db.Column(db.String(50))
    CabinFilterPartNumber2 = db.Column(db.String(50))
    PhotoOfCabinFilter2 = db.Column(db.String(50))
    CommentsOnCabinFilter2 = db.Column(db.String(50))
    CabinFilterPartNumber3 = db.Column(db.String(50))
    PhotoOfCabinFilter3 = db.Column(db.String(50))
    CommentsOnCabinFilter3 = db.Column(db.String(50))
    CabinFilterPartNumber4 = db.Column(db.String(50))
    PhotoOfCabinFilter4 = db.Column(db.String(50))
    CommentsOnCabinFilter4 = db.Column(db.String(50))
    CabinFilterPartNumber5 = db.Column(db.String(50))
    PhotoOfCabinFilter5 = db.Column(db.String(50))
    CommentsOnCabinFilter5 = db.Column(db.String(50))
    CabinFilterPartNumber6 = db.Column(db.String(50))
    PhotoOfCabinFilter6 = db.Column(db.String(50))
    CommentsOnCabinFilter6 = db.Column(db.String(50))
    CabinFilterPartNumber7 = db.Column(db.String(50))
    PhotoOfCabinFilter7 = db.Column(db.String(50))
    CommentsOnCabinFilter7 = db.Column(db.String(50))
    CabinFilterPartNumber8 = db.Column(db.String(50))
    PhotoOfCabinFilter8 = db.Column(db.String(50))
    CommentsOnCabinFilter8 = db.Column(db.String(50))
    AirCleanerModel = db.Column(db.String(50))
    PhotoOfAirCleanerArrangement1 = db.Column(db.String(50))
    PrimaryElememtPartNumber1 = db.Column(db.String(50))
    PrimaryElementDateCode1 = db.Column(db.String(50))
    PhotoOfPrimaryAirCleanerElement1 = db.Column(db.String(50))
    CommentsOnPrimaryAirCleanerElement1 = db.Column(db.String(50))
    SafetyElementPartNumber = db.Column(db.String(50))
    SafetyElementDateCode = db.Column(db.String(50))
    CommentsOnSafetyElement = db.Column(db.String(50))
    PhotoOfAirCleanerOutlet = db.Column(db.String(50))
    CommentsOnAirCleanerOutlet = db.Column(db.String(50))
    PhotoOfCleanAirDucting = db.Column(db.String(50))
    CommentsOnCleanAirDucting = db.Column(db.String(50))
    RestrictionIndicatorPartNumber = db.Column(db.String(50))
    RestrictionIndicatorValue = db.Column(db.String(50))
    PhotoOfRestrictionIndicator = db.Column(db.String(50))
    CommentsOnRestictionIndicator = db.Column(db.String(50))
    VacuatorValvesPartNumber1 = db.Column(db.String(50))
    PhotoOfVacuatorValves1 = db.Column(db.String(50))
    CommentsOnVacuatorValves1 = db.Column(db.String(50))
    VacuatorValvesPartNumber2 = db.Column(db.String(50))
    PhotoOfVacuatorValves2 = db.Column(db.String(50))
    CommentsOnVacuatorValves2 = db.Column(db.String(50))
    VacuatorValvesPartNumber3 = db.Column(db.String(50))
    PhotoOfVacuatorValves3 = db.Column(db.String(50))
    CommentsOnVacuatorValves3 = db.Column(db.String(50))
    VacuatorValvesPartNumber4 = db.Column(db.String(50))
    PhotoOfVacuatorValves4 = db.Column(db.String(50))
    CommentsOnVacuatorValves4 = db.Column(db.String(50))
    VacuatorValvesPartNumber5 = db.Column(db.String(50))
    PhotoOfVacuatorValves5 = db.Column(db.String(50))
    CommentsOnVacuatorValves5 = db.Column(db.String(50))
    VacuatorValvesPartNumber6 = db.Column(db.String(50))
    PhotoOfVacuatorValves6 = db.Column(db.String(50))
    CommentsOnVacuatorValves6 = db.Column(db.String(50))
    VacuatorValvesPartNumber7 = db.Column(db.String(50))
    PhotoOfVacuatorValves7 = db.Column(db.String(50))
    CommentsOnVacuatorValves7 = db.Column(db.String(50))
    VacuatorValvesPartNumber8 = db.Column(db.String(50))
    PhotoOfVacuatorValves8 = db.Column(db.String(50))
    CommentsOnVacuatorValves8 = db.Column(db.String(50))
    OtherObservationPartNumber1 = db.Column(db.String(50))
    PhotoOfOtherObservation1 = db.Column(db.String(50))
    CommentsOnOtherObservation1 = db.Column(db.String(50))
    OtherObservationPartNumber2 = db.Column(db.String(50))
    PhotoOfOtherObservation2 = db.Column(db.String(50))
    CommentsOnOtherObservation2 = db.Column(db.String(50))
    OtherObservationPartNumber3 = db.Column(db.String(50))
    PhotoOfOtherObservation3 = db.Column(db.String(50))
    CommentsOnOtherObservation3 = db.Column(db.String(50))
    OtherObservationPartNumber4 = db.Column(db.String(50))
    PhotoOfOtherObservation4 = db.Column(db.String(50))
    CommentsOnOtherObservation4 = db.Column(db.String(50))
    OtherObservationPartNumber5 = db.Column(db.String(50))
    PhotoOfOtherObservation5 = db.Column(db.String(50))
    CommentsOnOtherObservation5 = db.Column(db.String(50))
    OtherObservationPartNumber6 = db.Column(db.String(50))
    PhotoOfOtherObservation6 = db.Column(db.String(50))
    CommentsOnOtherObservation6 = db.Column(db.String(50))
    OtherObservationPartNumber7 = db.Column(db.String(50))
    PhotoOfOtherObservation7 = db.Column(db.String(50))
    CommentsOnOtherObservation7 = db.Column(db.String(50))
    OtherObservationPartNumber8 = db.Column(db.String(50))
    PhotoOfOtherObservation8 = db.Column(db.String(50))
    CommentsOnOtherObservation8 = db.Column(db.String(50))
    ExhaustInspectionPartNumber1 = db.Column(db.String(50))
    PhotoOfExhaustInpection1 = db.Column(db.String(50))
    CommentsOnExhaustInspection1 = db.Column(db.String(50))
    ExhaustInspectionPartNumber2 = db.Column(db.String(50))
    PhotoOfExhaustInpection2 = db.Column(db.String(50))
    CommentsOnExhaustInspection2 = db.Column(db.String(50))
    ExhaustInspectionPartNumber3 = db.Column(db.String(50))
    PhotoOfExhaustInpection3 = db.Column(db.String(50))
    CommentsOnExhaustInspection3 = db.Column(db.String(50))
    ExhaustInspectionPartNumber4 = db.Column(db.String(50))
    PhotoOfExhaustInpection4 = db.Column(db.String(50))
    CommentsOnExhaustInspection4 = db.Column(db.String(50))
    ExhaustInspectionPartNumber5 = db.Column(db.String(50))
    PhotoOfExhaustInpection5 = db.Column(db.String(50))
    CommentsOnExhaustInspection5 = db.Column(db.String(50))
    ExhaustInspectionPartNumber6 = db.Column(db.String(50))
    PhotoOfExhaustInpection6 = db.Column(db.String(50))
    CommentsOnExhaustInspection6 = db.Column(db.String(50))
    ExhaustInspectionPartNumber7 = db.Column(db.String(50))
    PhotoOfExhaustInpection7 = db.Column(db.String(50))
    CommentsOnExhaustInspection7 = db.Column(db.String(50))
    ExhaustInspectionPartNumber8 = db.Column(db.String(50))
    PhotoOfExhaustInpection8 = db.Column(db.String(50))
    CommentsOnExhaustInspection8 = db.Column(db.String(50))
    GeneralComments = db.Column(db.String(50))
    EmailReportTo = db.Column(db.String(50))

    # Display the details of our code
    def __repr__(self) -> str:
        return f"{self.PlantInspectionID} {self.CustomerName}"

#Create Birth_Certificate Table Here:

class Birth_Certificate(db.Model):
    BirthCertificateID = db.Column(db.Integer, primary_key=True)
    CustomerName = db.Column(db.String(200))
    CustomerSite = db.Column(db.String(50))
    Date = db.Column(db.String, default=lambda: datetime.now().strftime("%d/%m/%Y"))
    Time = db.Column(db.String, default=lambda: datetime.now().strftime("%I:%M %p"))
    ContactPerson = db.Column(db.String(50))
    InspectedBy = db.Column(db.String(50))
    InspectionAssistant = db.Column(db.String(50))
    PlantNumber = db.Column(db.String(50))
    PlantMake = db.Column(db.String(50))
    PlantModel = db.Column(db.String(50))
    SerialNumber = db.Column(db.String(50))
    PlantKmsHrs = db.Column(db.String(50))
    EngineMake = db.Column(db.String(50))
    EngineModel = db.Column(db.String(50))
    EngineSerialNumber = db.Column(db.String(50))
    PriamryFuelFilterPartNumber = db.Column(db.String(50))
    PrimaryFuelFilterPhoto = db.Column(db.String(50))
    CommentsOnFuelFilter = db.Column(db.String(50))
    SecondaryFuelFilterPartNumber = db.Column(db.String(50))
    SecondaryFuelFilterPhoto = db.Column(db.String(50))
    CommentsOnSecondaryFuelFilter = db.Column(db.String(50))
    FuelWaterSeparatorPartNumber = db.Column(db.String(50))
    PhotoOfFuelWaterSeparator = db.Column(db.String(50))
    CommentsOnFuelWaterSeparator = db.Column(db.String(50))
    OilFilterPartNumber = db.Column(db.String(50))
    PhotoOfOilFilter = db.Column(db.String(50))
    CommentsOnOilFilter = db.Column(db.String(50))
    BypassOilFilterPartNumber = db.Column(db.String(50))
    PhotoOfBypassOilFilter = db.Column(db.String(50))
    CommentsOnBypassOilFilter = db.Column(db.String(50))
    HydraulicFilterPartNumber1 = db.Column(db.String(50))
    PhotoOfHydraulicFilter1 = db.Column(db.String(50))
    CommentsOnHydraulicFilter1 = db.Column(db.String(50))
    HydraulicFilterPartNumber2 = db.Column(db.String(50))
    PhotoOfHydraulicFilter2 = db.Column(db.String(50))
    CommentsOnHydraulicFilter2 = db.Column(db.String(50))
    HydraulicFilterPartNumber3 = db.Column(db.String(50))
    PhotoOfHydraulicFilter3 = db.Column(db.String(50))
    CommentsOnHydraulicFilter3 = db.Column(db.String(50))
    HydraulicFilterPartNumber4 = db.Column(db.String(50))
    PhotoOfHydraulicFilter4 = db.Column(db.String(50))
    CommentsOnHydraulicFilter4 = db.Column(db.String(50))
    HydraulicFilterPartNumber5 = db.Column(db.String(50))
    PhotoOfHydraulicFilter5 = db.Column(db.String(50))
    CommentsOnHydraulicFilter5 = db.Column(db.String(50))
    HydraulicFilterPartNumber6 = db.Column(db.String(50))
    PhotoOfHydraulicFilter6 = db.Column(db.String(50))
    CommentsOnHydraulicFilter6 = db.Column(db.String(50))
    HydraulicFilterPartNumber7 = db.Column(db.String(50))
    PhotoOfHydraulicFilter7 = db.Column(db.String(50))
    CommentsOnHydraulicFilter7 = db.Column(db.String(50))
    HydraulicFilterPartNumber8 = db.Column(db.String(50))
    PhotoOfHydraulicFilter8 = db.Column(db.String(50))
    CommentsOnHydraulicFilter8 = db.Column(db.String(50))
    TransmissionFilterPartNumber1 = db.Column(db.String(50))
    PhotoOfTransmissionFilter1 = db.Column(db.String(50))
    CommentsOnTransmissionFilter1 = db.Column(db.String(50))
    TransmissionFilterPartNumber2 = db.Column(db.String(50))
    PhotoOfTransmissionFilter2 = db.Column(db.String(50))
    CommentsOnTransmissionFilter2 = db.Column(db.String(50))
    TransmissionFilterPartNumber3 = db.Column(db.String(50))
    PhotoOfTransmissionFilter3 = db.Column(db.String(50))
    CommentsOnTransmissionFilter3 = db.Column(db.String(50))
    TransmissionFilterPartNumber4 = db.Column(db.String(50))
    PhotoOfTransmissionFilter4 = db.Column(db.String(50))
    CommentsOnTransmissionFilter4 = db.Column(db.String(50))
    TransmissionFilterPartNumber5 = db.Column(db.String(50))
    PhotoOfTransmissionFilter5 = db.Column(db.String(50))
    CommentsOnTransmissionFilter5 = db.Column(db.String(50))
    TransmissionFilterPartNumber6 = db.Column(db.String(50))
    PhotoOfTransmissionFilter6 = db.Column(db.String(50))
    CommentsOnTransmissionFilter6 = db.Column(db.String(50))
    TransmissionFilterPartNumber7 = db.Column(db.String(50))
    PhotoOfTransmissionFilter7 = db.Column(db.String(50))
    CommentsOnTransmissionFilter7 = db.Column(db.String(50))
    TransmissionFilterPartNumber8 = db.Column(db.String(50))
    PhotoOfTransmissionFilter8 = db.Column(db.String(50))
    CommentsOnTransmissionFilter8 = db.Column(db.String(50))
    CoolantFiltersPartNumber1 = db.Column(db.String(50))
    PhotoOfCoolantFilter1 = db.Column(db.String(50))
    CommentsOnCoolantFilter1 = db.Column(db.String(50))
    CoolantFiltersPartNumber2 = db.Column(db.String(50))
    PhotoOfCoolantFilter2 = db.Column(db.String(50))
    CommentsOnCoolantFilter2 = db.Column(db.String(50))
    CoolantFiltersPartNumber3 = db.Column(db.String(50))
    PhotoOfCoolantFilter3 = db.Column(db.String(50))
    CommentsOnCoolantFilter3 = db.Column(db.String(50))
    CoolantFiltersPartNumber4 = db.Column(db.String(50))
    PhotoOfCoolantFilter4 = db.Column(db.String(50))
    CommentsOnCoolantFilter4 = db.Column(db.String(50))
    CoolantFiltersPartNumber5 = db.Column(db.String(50))
    PhotoOfCoolantFilter5 = db.Column(db.String(50))
    CommentsOnCoolantFilter5 = db.Column(db.String(50))
    CoolantFiltersPartNumber6 = db.Column(db.String(50))
    PhotoOfCoolantFilter6 = db.Column(db.String(50))
    CommentsOnCoolantFilter6 = db.Column(db.String(50))
    CoolantFiltersPartNumber7 = db.Column(db.String(50))
    PhotoOfCoolantFilter7 = db.Column(db.String(50))
    CommentsOnCoolantFilter7 = db.Column(db.String(50))
    CoolantFiltersPartNumber8 = db.Column(db.String(50))
    PhotoOfCoolantFilter8 = db.Column(db.String(50))
    CommentsOnCoolantFilter8 = db.Column(db.String(50))
    BreatherFilterPartNumber1 = db.Column(db.String(50))
    PhotoOfBreatherFilter1 = db.Column(db.String(50))
    CommentsOnBreatherFilter1 = db.Column(db.String(50))
    BreatherFilterPartNumber2 = db.Column(db.String(50))
    PhotoOfBreatherFilter2 = db.Column(db.String(50))
    CommentsOnBreatherFilter2 = db.Column(db.String(50))
    BreatherFilterPartNumber3 = db.Column(db.String(50))
    PhotoOfBreatherFilter3 = db.Column(db.String(50))
    CommentsOnBreatherFilter3 = db.Column(db.String(50))
    BreatherFilterPartNumber4 = db.Column(db.String(50))
    PhotoOfBreatherFilter4 = db.Column(db.String(50))
    CommentsOnBreatherFilter4 = db.Column(db.String(50))
    BreatherFilterPartNumber5 = db.Column(db.String(50))
    PhotoOfBreatherFilter5 = db.Column(db.String(50))
    CommentsOnBreatherFilter5 = db.Column(db.String(50))
    BreatherFilterPartNumber6 = db.Column(db.String(50))
    PhotoOfBreatherFilter6 = db.Column(db.String(50))
    CommentsOnBreatherFilter6 = db.Column(db.String(50))
    BreatherFilterPartNumber7 = db.Column(db.String(50))
    PhotoOfBreatherFilter7 = db.Column(db.String(50))
    CommentsOnBreatherFilter7 = db.Column(db.String(50))
    BreatherFilterPartNumber8 = db.Column(db.String(50))
    PhotoOfBreatherFilter8 = db.Column(db.String(50))
    CommentsOnBreatherFilter8 = db.Column(db.String(50))
    AirDryerPartNumber1 = db.Column(db.String(50))
    PhotoOfAirDryer1 = db.Column(db.String(50))
    CommentsOfAirDryer1 = db.Column(db.String(50))
    AirDryerPartNumber2 = db.Column(db.String(50))
    PhotoOfAirDryer2 = db.Column(db.String(50))
    CommentsOfAirDryer2 = db.Column(db.String(50))
    AirDryerPartNumber3 = db.Column(db.String(50))
    PhotoOfAirDryer3 = db.Column(db.String(50))
    CommentsOfAirDryer3 = db.Column(db.String(50))
    AirDryerPartNumber4 = db.Column(db.String(50))
    PhotoOfAirDryer4 = db.Column(db.String(50))
    CommentsOfAirDryer4 = db.Column(db.String(50))
    AirDryerPartNumber5 = db.Column(db.String(50))
    PhotoOfAirDryer5 = db.Column(db.String(50))
    CommentsOfAirDryer5 = db.Column(db.String(50))
    AirDryerPartNumber6 = db.Column(db.String(50))
    PhotoOfAirDryer6 = db.Column(db.String(50))
    CommentsOfAirDryer6 = db.Column(db.String(50))
    AirDryerPartNumber7 = db.Column(db.String(50))
    PhotoOfAirDryer7 = db.Column(db.String(50))
    CommentsOfAirDryer7 = db.Column(db.String(50))
    AirDryerPartNumber8 = db.Column(db.String(50))
    PhotoOfAirDryer8 = db.Column(db.String(50))
    CommentsOfAirDryer8 = db.Column(db.String(50))
    CabinFilterPartNumber1 = db.Column(db.String(50))
    PhotoOfCabinFilter1 = db.Column(db.String(50))
    CommentsOnCabinFilter1 = db.Column(db.String(50))
    CabinFilterPartNumber2 = db.Column(db.String(50))
    PhotoOfCabinFilter2 = db.Column(db.String(50))
    CommentsOnCabinFilter2 = db.Column(db.String(50))
    CabinFilterPartNumber3 = db.Column(db.String(50))
    PhotoOfCabinFilter3 = db.Column(db.String(50))
    CommentsOnCabinFilter3 = db.Column(db.String(50))
    CabinFilterPartNumber4 = db.Column(db.String(50))
    PhotoOfCabinFilter4 = db.Column(db.String(50))
    CommentsOnCabinFilter4 = db.Column(db.String(50))
    CabinFilterPartNumber5 = db.Column(db.String(50))
    PhotoOfCabinFilter5 = db.Column(db.String(50))
    CommentsOnCabinFilter5 = db.Column(db.String(50))
    CabinFilterPartNumber6 = db.Column(db.String(50))
    PhotoOfCabinFilter6 = db.Column(db.String(50))
    CommentsOnCabinFilter6 = db.Column(db.String(50))
    CabinFilterPartNumber7 = db.Column(db.String(50))
    PhotoOfCabinFilter7 = db.Column(db.String(50))
    CommentsOnCabinFilter7 = db.Column(db.String(50))
    CabinFilterPartNumber8 = db.Column(db.String(50))
    PhotoOfCabinFilter8 = db.Column(db.String(50))
    CommentsOnCabinFilter8 = db.Column(db.String(50))
    AirCleanerModel = db.Column(db.String(50))
    PhotoOfAirCleanerArrangement1 = db.Column(db.String(50))
    PrimaryElememtPartNumber1 = db.Column(db.String(50))
    PrimaryElementDateCode1 = db.Column(db.String(50))
    PhotoOfPrimaryAirCleanerElement1 = db.Column(db.String(50))
    CommentsOnPrimaryAirCleanerElement1 = db.Column(db.String(50))
    SafetyElementPartNumber = db.Column(db.String(50))
    SafetyElementDateCode = db.Column(db.String(50))
    CommentsOnSafetyElement = db.Column(db.String(50))
    PhotoOfAirCleanerOutlet = db.Column(db.String(50))
    CommentsOnAirCleanerOutlet = db.Column(db.String(50))
    PhotoOfCleanAirDucting = db.Column(db.String(50))
    CommentsOnCleanAirDucting = db.Column(db.String(50))
    RestrictionIndicatorPartNumber = db.Column(db.String(50))
    RestrictionIndicatorValue = db.Column(db.String(50))
    PhotoOfRestrictionIndicator = db.Column(db.String(50))
    CommentsOnRestictionIndicator = db.Column(db.String(50))
    VacuatorValvesPartNumber1 = db.Column(db.String(50))
    PhotoOfVacuatorValves1 = db.Column(db.String(50))
    CommentsOnVacuatorValves1 = db.Column(db.String(50))
    VacuatorValvesPartNumber2 = db.Column(db.String(50))
    PhotoOfVacuatorValves2 = db.Column(db.String(50))
    CommentsOnVacuatorValves2 = db.Column(db.String(50))
    VacuatorValvesPartNumber3 = db.Column(db.String(50))
    PhotoOfVacuatorValves3 = db.Column(db.String(50))
    CommentsOnVacuatorValves3 = db.Column(db.String(50))
    VacuatorValvesPartNumber4 = db.Column(db.String(50))
    PhotoOfVacuatorValves4 = db.Column(db.String(50))
    CommentsOnVacuatorValves4 = db.Column(db.String(50))
    VacuatorValvesPartNumber5 = db.Column(db.String(50))
    PhotoOfVacuatorValves5 = db.Column(db.String(50))
    CommentsOnVacuatorValves5 = db.Column(db.String(50))
    VacuatorValvesPartNumber6 = db.Column(db.String(50))
    PhotoOfVacuatorValves6 = db.Column(db.String(50))
    CommentsOnVacuatorValves6 = db.Column(db.String(50))
    VacuatorValvesPartNumber7 = db.Column(db.String(50))
    PhotoOfVacuatorValves7 = db.Column(db.String(50))
    CommentsOnVacuatorValves7 = db.Column(db.String(50))
    VacuatorValvesPartNumber8 = db.Column(db.String(50))
    PhotoOfVacuatorValves8 = db.Column(db.String(50))
    CommentsOnVacuatorValves8 = db.Column(db.String(50))
    OtherObservationPartNumber1 = db.Column(db.String(50))
    PhotoOfOtherObservation1 = db.Column(db.String(50))
    CommentsOnOtherObservation1 = db.Column(db.String(50))
    OtherObservationPartNumber2 = db.Column(db.String(50))
    PhotoOfOtherObservation2 = db.Column(db.String(50))
    CommentsOnOtherObservation2 = db.Column(db.String(50))
    OtherObservationPartNumber3 = db.Column(db.String(50))
    PhotoOfOtherObservation3 = db.Column(db.String(50))
    CommentsOnOtherObservation3 = db.Column(db.String(50))
    OtherObservationPartNumber4 = db.Column(db.String(50))
    PhotoOfOtherObservation4 = db.Column(db.String(50))
    CommentsOnOtherObservation4 = db.Column(db.String(50))
    OtherObservationPartNumber5 = db.Column(db.String(50))
    PhotoOfOtherObservation5 = db.Column(db.String(50))
    CommentsOnOtherObservation5 = db.Column(db.String(50))
    OtherObservationPartNumber6 = db.Column(db.String(50))
    PhotoOfOtherObservation6 = db.Column(db.String(50))
    CommentsOnOtherObservation6 = db.Column(db.String(50))
    OtherObservationPartNumber7 = db.Column(db.String(50))
    PhotoOfOtherObservation7 = db.Column(db.String(50))
    CommentsOnOtherObservation7 = db.Column(db.String(50))
    OtherObservationPartNumber8 = db.Column(db.String(50))
    PhotoOfOtherObservation8 = db.Column(db.String(50))
    CommentsOnOtherObservation8 = db.Column(db.String(50))
    ExhaustInspectionPartNumber1 = db.Column(db.String(50))
    PhotoOfExhaustInpection1 = db.Column(db.String(50))
    CommentsOnExhaustInspection1 = db.Column(db.String(50))
    ExhaustInspectionPartNumber2 = db.Column(db.String(50))
    PhotoOfExhaustInpection2 = db.Column(db.String(50))
    CommentsOnExhaustInspection2 = db.Column(db.String(50))
    ExhaustInspectionPartNumber3 = db.Column(db.String(50))
    PhotoOfExhaustInpection3 = db.Column(db.String(50))
    CommentsOnExhaustInspection3 = db.Column(db.String(50))
    ExhaustInspectionPartNumber4 = db.Column(db.String(50))
    PhotoOfExhaustInpection4 = db.Column(db.String(50))
    CommentsOnExhaustInspection4 = db.Column(db.String(50))
    ExhaustInspectionPartNumber5 = db.Column(db.String(50))
    PhotoOfExhaustInpection5 = db.Column(db.String(50))
    CommentsOnExhaustInspection5 = db.Column(db.String(50))
    ExhaustInspectionPartNumber6 = db.Column(db.String(50))
    PhotoOfExhaustInpection6 = db.Column(db.String(50))
    CommentsOnExhaustInspection6 = db.Column(db.String(50))
    ExhaustInspectionPartNumber7 = db.Column(db.String(50))
    PhotoOfExhaustInpection7 = db.Column(db.String(50))
    CommentsOnExhaustInspection7 = db.Column(db.String(50))
    ExhaustInspectionPartNumber8 = db.Column(db.String(50))
    PhotoOfExhaustInpection8 = db.Column(db.String(50))
    CommentsOnExhaustInspection8 = db.Column(db.String(50))
    GeneralComments = db.Column(db.String(50))
    EmailReportTo = db.Column(db.String(50))

    # Display the details of our code
    def __repr__(self) -> str:
        return f"{self.BirthCertificateID} {self.CustomerName}"

# Our homepage
@app.route("/", methods=['GET', 'POST'])
def hello_world():

    technicalInstallations = Technical_Installation.query.all()
    plantInspections = Plant_Inspection.query.all()
    birthCertificates = Birth_Certificate.query.all()
    exhaustInspections = Exhaust_Inspection.query.all()
    return render_template('index.html', technicalInstallations=technicalInstallations, plantInspections=plantInspections, 
                           birthCertificates=birthCertificates, exhaustInspections=exhaustInspections)

# Delete Technical Installation
@app.route("/delete/<int:TechnicalInstallationID>")
def delete(technicalInstallationID):
    technicalInstallation = Technical_Installation.query.filter_by(
            TechnicalInstallationID=technicalInstallationID).first()
    if technicalInstallation:
        db.session.delete(technicalInstallation)
        db.session.commit()
    return redirect('/')

@app.route('/about')
def about():
    return render_template('about.html')

@app.route('/plant')
def plant():
    return render_template('plant.html')

@app.route('/exhaust')
def exhaust():
    return render_template('exhaust.html')

@app.route('/technical')
def technical():
    return render_template('technical.html')

@app.route('/certificates')
def certificates():
    return render_template('certificates.html')

@app.route('/privacy-policy')
def privacy():
    return render_template('privacy.html')

@app.route('/update/<int:technicalInstallationID>', methods=['GET', 'POST'])
def update(technicalInstallationID):
    technicalInstallation = TechnicalInstallation.query.filter_by(
            TechnicalInstallationID=technicalInstallationID).first()
    if request.method == 'POST':
        if technicalInstallation:
            technicalInstallation.TechnicalInstallationID = request.form['installationID']
            technicalInstallation.CustomerName = request.form['customerName']
            technicalInstallation.CutomerSite = request.form['customerSite']
            technicalInstallation.JobNumber = request.form['jobNumber']
            technicalInstallation.InvoiceNumber = request.form['invoiceNumber']
            technicalInstallation.PlantMake = request.form['plantMake']
            technicalInstallation.PlantModel = request.form['plantModel']
            technicalInstallation.SerialNumber = request.form['serialNumber']
            technicalInstallation.EngineMake = request.form['engineMake']
            technicalInstallation.EngineModel = request.form['engineModel']
            technicalInstallation.EngineSerialNumber = request.form['engineSerialNumber']
            technicalInstallation.PlantNumber = request.form['plantNumber']
            technicalInstallation.PlantKmsHrs = request.form['plantKmsHrs']
            technicalInstallation.WarrantyStartDate = request.form['warrantyStartDate']
            technicalInstallation.WarrantyEndDate = request.form['warrantyEndDate']
            technicalInstallation.InstallationPhoto1 = request.form['installationPhoto1']
            technicalInstallation.InstallationPhoto2 = request.form['installationPhoto2']
            technicalInstallation.InstallationPhoto3 = request.form['installationPhoto3']
            technicalInstallation.InstallationPhoto4 = request.form['installationPhoto4']
            technicalInstallation.InstallationPhoto5 = request.form['installationPhoto5']
            technicalInstallation.InstallationPhoto6 = request.form['installationPhoto6']
            technicalInstallation.AdditionalCommentsSuggestions = request.form['additionalSuggestions']
            technicalInstallation.CustomerFullName = request.form['customerFullName']
            technicalInstallation.CustomerDate = request.form['customerDate']
            technicalInstallation.TechnitianFullName = request.form['technitianFullName']
            technicalInstallation.TechnitianDate = request.form['technitianDate']
            technicalInstallation.EmailReportTo = request.form['emailReportTo']

            db.session.commit()
        return redirect('/')
    return render_template('update.html', technicalInstallation = technicalInstallation)

if __name__ == '__main__':
    with app.app_context():
        db.create_all()
    app.run(debug=True, host = '0.0.0.0')

